#+title: January 2 2023 Who Is The Owner Of Everything?

#+begin_quote
  [...] for the world is mine, and all that is in it - Psalm 50:12
#+end_quote

God told David that he couldn’t build the temple, so his son Solomon would do it. David prepared all the materials needed (1Chr. 22:6-10, 14).

Then, David invited the people to bring a special offering for the construction(1Chr. 29:6-10). David responded to their generosity by praying as follows (1Chr. 29:11-16 NIV):

- “Everything in heaven and earth is Yours” (11)
- “Wealth and honor come from You” (12)
- “Everything comes from You” (14)
- “We have given You only what comes from Your hand” (14)
- “All this abundance […] comes from Your hand” (16)
- “All of it belongs to You” (16)

Everything we have is God’s. Therefore, we must praise Him and thank Him for His kindness.

** E.G.W. (Partriarchs and Prophets, cp. 73, p. 753)

All that man receives of God’s bounty still belongs to God. Whatever God has bestowed in the valuable and beautiful things of earth is placed in the hands of men to test them — to sound the depths of their for Him and thier appreciation of His favors. Whether it be the treasures of wealth or of intellect, they are to be laid, a willing offering, at the feet of Jesus; the giver saying, meanwhile, with David, “All things come of Thee, and of Thine own have we given Thee.”
