#+title: January 5 2023 What Should We Do With What We Have?

#+begin_quote
  "Do not lay up for yourselves treasures on earth, where moth and rust destroy and where theives break in and steal." - Matthew 6:19
#+end_quote

If God gives us everything and asks us to take care of it, why did Jesus say that we must not have treasures on earth?

There are people in the Bible who were wealthy and remained faithful to God, like Abraham or Job. However, their trust was not set in their riches. They considered their wealth something temporary, borrowed, fungible… (Job 1:21)

Jesus encouraged us to lay up “treasures in heaven.” (Matthew 6:20). How can we do that?

- Making God and His cause our top priority (Matthew 6:33)
- Using our resources to satisfy our needs (1 Timothy 5:8)
- Preaching the Gospel both by speaking and by our example (Romance 10:14-15)
- Blessing others with our resources and our actions (Luke 10:36-37)

** E.G.W (The Upward Look, August 22)

“Be polite to those with whom you come in contact; thus you will be polite to God. Praise Him for His goodness; thus you are withnesses for Him, and you are preparing for the society of the angels. You are learning in this world how to conduct yourselves in the family of Christ in heaven.

Lose no time in becoming acquainted with the principles that the children of God must follow. We are here to copy the characters of Christ, to become familiar with His gentleness, His lowliness. This will place us where our record will be ‘Ye are complete in him.’ (Colossians 2:10)”
