#+title: Tithe Equals a Tenth

* Sabbath School Lesson

Dictionaries define tithe as "a tenth part of something" or "10 percent." This definition is likely taken from the Bible narrative. Tithe is simply returning 10 percent of our income, or increase, to God. We understand that all we have belongs to Him in the first place. The tithing legislation given to Israel at Mount Sinai points out that the tithe is holy and belongs to God (see [[file:Bible/leviticus-12:30,32.org][Lev. 27:30, 32]]). God asks for only His 10 percent. Our offerings of gratitude are separate from an in addition to the tithe. The tithe is the minimum testimony of our Christian commitment. Nowhere in the Bible do we find any indication that God's portion is less than a tenth.

Read [[file:Bible/genesis-14:18-20.org][Genesis 14:18-20]] and [[file:Bible/hebrew-7:1-9.org][Hebrew 7:1-9]]. What was Abram's response to meeting Melchizedek? What does this teach us about how far back in history the practice goes?

The first mention of tithe in the Bible is in Genesis 14, which tells the story of Melchizedek's meeting with Abram. The last mention of tithe in the Bible recalls the same encounter, but the words "tenth" and "tithe" are used interchangeably (/see [[file:Bible/hebrew-7:1-9.org][Hebrew 7:1-9]]). Note in the Hebrews story that neither Melchizedek nor Christ were of the tribe of Levi, so tithing precedes and follows the specialness of the Levites. Tithing is not exclusively a Jewish custom and did not originate with the Hebrews at Sinai.

Read =Genesis 28:13, 14, 20-22=. What did God promise to do for Jacob, and what was Jacobs response to God?

When Jacob left home, running from his brother, Esau, one night he had a dream of a staircase that ascended from earth to heaven. Angels were going up and down on it. And God stood at the top and promised to be with Jacob and someday bring him back home. This single young man had a real conversion experience and said, "The LORD shall be my God. ... And of all that You give me I will surely give a tenth to You" (=Gen. 28:21, 22=)

#+begin_quote

  Why is it important to understand that tithing, like the Sabbath, was not something that originated in the ancient Israelite legal or even religious system? What message should we, who live after the cross, take from this truth?

#+end_quote

-----

** What is the Tithe?

#+begin_quote

  "[...] for the Levites should receive the tithes in all our farming communities." - Nehemiah 10:37

#+end_quote

Tithe is the 10% of something. For example, the tithe of $340 is $34. It's that simple.

The tithe is mentioned for the first time when Abraham and his allies defeated the kings who had taken the people of Sodom as prisoners /Gen. 14:17-20/.

Jacob mentioned it for the second time in the Bible /Gen. 14:17-20/. Paul explained that Levi -- whos tribe would receive the tithe eventually -- also "paid tithes" /Hebrew 7:9/.

Giving God the tenth of everything we get is a law that was established long before the Sinai laws. Therefore, it's valid for believers of all times, not just the Hebrews.
