#+title: The Tithing Contract

#+begin_quote

  "Bring all the tithes into the storehouse, that there may be food in My house, and try Me no in this, 'says the LORD of hosts, 'if I will not open for you the windows of heaven and pour out for your such blessing that there will not be room enough to receive it." - Malachi 3:10, NKJV

#+end_quote

In Genesis 14, Abram had returned from a successful hostage rescue mission in which he had saved his nephew Lot, Lot's family, and the other people taken from Sodom. The king of Sodom was so grateful for the rescue that he offered Abram all the spoils of the battle. Abram not only refused the offer but gave a tithe of all that he possessed to Melchizedek.

Immediately after Abram's tithing experience, the Lord said, "Do not be afraid, Abram. I am your shield, your exceedingly great reward" /Genesis 15:1/. In effect, the Lord was telling Abram, "Don't worry. I will be your protector and provider." Then, much later, Moses told Israel as they were about to enter Canaan, "You shall truly tithe all the increase of your grain that the field produces year by year ... that you may learn to fear the LORD your God always." /Deuteronomi 14:22, 23/.

Ellen G. White wrote: "Men were required to offer to God gifts for religious purposes before the definite system was given to Moses, even as far back as the days of Adam." -- [[https://ssnet.org/lessons/23a/helps/lesshp03.html#egw01][Testimonies for the Church, vol. 3, p. 393]].

-----

In Malachi 3:10, God proposed a contract with His people: "Bring me the tithes, and I will bless you."

Is this a contract for the people of Israel only?

Are Christians excluded from the benefits of that contract? We are not! Therefore, we must thoroughly study how to fulfill our part of the contract.

- What is the tithe?
- How should it be given?
- How should it be used?
- What must be tithed?
- Faithful tithing
