#+title: Where Is the Storehouse?

* Sabbath School Lesson

=Read Malachi 3:10=. What can we learn from this verse about where our tithe should go?

-----

Though specific directions are not given in the text, it is nevertheless evident that God's people knew what He meant by the word "storehouse." God does include in His directions, "that thre may be food in My house" (NKJV). His people understood that God's house initially was the sanctuary -- the elaborate tent that was build by specific directions given to Moses at Mount Sinai. Later when Israel lived in the Promised Land, the central location was first in Shiloh and then more permanently at the temple in Jerusalem.

=Read Deuteronomy 12:5-14=. These verses do not indicate that God's children could use their own discretion as to where their tithe was deposited. What principles can we take from these verses for ourselves today?

-----

As members of God's family, we want to understand and practice His will regarding what to do with our tithe. In the biblical narrative, we learn that three times in each year -- Passover, Pentecost, and Feast of Tabernacles =Exodus 23:14-17= -- God's people were to travel to Jerusalem to bring their tithes and offerings personally and to praise and to worship God. Then the Levites distributed the tithe to their brethren all over the land of Israel (see =2 Chron. 31:11-21, Neh. 12:44-47, Neh. 13:8-14=). In harmony with this biblical central storehouse principle, the Seventh-day Adventist Church has designated the local conferences, missions, and unions of churches as storehouse on behalf of the world church, and from which the ministry is paid.

For the convenience of church members, the tithe is brought to the local church, where, as part of their worship experience, members bring their tithes and offerings, though some use online giving. The local treasurers then forward the tithe to the conference storehouse. This system of tithe management, outlined and ordained by God, has enabled the Seventh-day Adventist Church to have a worldwide and growing impact in the world.

#+begin_quote

  Imagine if everyone decided to give their tithe to whomever they wanted to, at the expense of the Adventist church itself. What would happen to our church? Why is that practice, then, such a bad idea and contrary to Scriptures?

#+end_quote

** How Should It Be Given?

#+begin_quote

  "Bring the full amount of your tithes to the Temple, so that there will be plenty of food there [...]" - Malachi 3:10

#+end_quote

The Bible talks about multi-year special tithes that had to be given to the poor =Deuteronomy 14:28-29=. However, the regular tithe had to be given **ALWAYS** to the Temple treasury =Mal. 3:10; Neh. 12:44=.

The treasury or storehouse was a special room attached to the temple where tithes were stored =2Chr 31:11-12=. When people lived too far away to carry the tithe of their sheep, grain, or fruits, they gave the equivalent cost instead =Deuteronomy 14:24-25=.

Nowadays, the tithe is given in the local churches. Then, it is sent to the treasury of their Conference, Union, or Mission.
