#+title: January 13 Further Thought

Further Thought: “Whenever God’s people, in any period of the world, have cheerfully and willingly carried out His plan in systematic benevolence [tithing] and in gifts and offerings, they have realize the standing promise that prosperity should attend all their labors just in proportion as they obeyed His requirements. When they acknowledged the claims of God and complied with His requirements, honoring Him with their substance, their barns were filled with plenty. But when they robbed God in tithes and in offerings they were made to realize that they were not only robbing Him but themselves, for He limited His blessings to them just in proportion as they limited their offerings to Him.” — [[https://ssnet.org/lessons/23a/helps/lesshp02.html#egw03][Ellen G. White, Testimonies for the Church, vol. 3, p. 395]].

The Bible is very clear that we are saved through faith alone, a gift of God’s grace. Our obedience to God’s commands is a response to God’s grace; it doesn’t earn it (after all, if it were earned, it woudn’t be grace: see *Romance 4:1-4*).

Indeed, when we look at God’s bilateral covenant with us, we can see both our blessings and our responsibilities. By our responses to what God offers to us, we establish our relationship with Him and, to a great degree, determine our own destiny. Obedience — the service and allegiance of love — is the true sign of descipleship. Instead of releasing us from obedience, it is faith, and faith only, that makes us partakers of the grace of Christ, which enables us to render the obedience that God asks from us.

** E.G.W (Testimonies for Ministers and Gospel Workers, cp.44, p.307)

“The Lord bestows His gifts abundantly upon us. He ‘so loved the world, that He gave His only-begotten Son, that whosoever believeth in Him should not perish, but have everlasting life.’ Every blessing we have comes through Jesus Christ. Then shall we not arouse, and do our duty toward God, upon whom we are dependent for life and health, for His blessing […]? We are assured if we give to the Lord’s treasury, we shall receive of Him again.”
