#+title: January 12 Seek Ye First

It was said of Jesus that “the common people heard him gladly” =Mark 12:37=. Most of the people in the large crowds who followed and listened to Jesus were members of this class, the common people. They were the ones who where fed on the mountainside, and who heard the Sermon on the Mount. Jesus said to them, basically, I know you are concerned about providing for your families. You worry about the food and drink that you will need daily and the clothin that you need for warmth and protection. But here is what I propose…

- =Matthew 6:25-33= *What are we asked to do in order to have the peace of God?*
- =John 1:9= *What will Jesus do if we confess our sins?*
- =2 Chronicles 7:14= *What are the “ifs” and “thens” of God’s proposal here?*

All these verses and many others deal with the important fact that although God is sovereign, although God is our Creator and Sustainerm and although salvation is a gift of grace and unmerited on our part, we still have a part to play in the great controversy drama here on earth. Using the sacred gift of free will, free choice, we must choose to follow the prompting of the Holy Spirit and obey what God calls us to do. Though God offers us blessings and life, we can choose cursing and death instead. No wonder God says, “Therefore choose life, that both you and your descendants may live” *Deuteronomy 30:19*

** Other Covenants

#+begin_quote
  "But seek first the kingdom of God and His righteousness, and all these things shall be added to you." - Matthew 6:33
#+end_quote

Jesus extended the covenant of the firstfruits: If we put God in first place, He will give us food and clothes, and He will satisfy our need *Matthew 6:25-34.*

There are other covenants in the Bible:

*** Covenant

- Covenant of peace *Isaiah 26:3*
- Covenant of forgiveness *1 John 1:9*
- Covenant of healing *2 Chronicles 7:14*

*** Our Part

- Trust God and think about Him
- Confess our sins
- Humble oneself, pray, seek God, repent

*** God’s Part

- Give us complete peace
- Forgive our sins and clean us from evil
- Heal our land


God always offers two options: either to obey and receive blessings or to disobey and lose the blessings. “therefore choose life [obeying], that both you and your descendants may live [receive blessings].” *Deuteronomy 30:19*
