#+title: Hebrew 7:1-9

For this Melchizedek, king of Salem, priest of the Most High God, who met Abraham returning from the slaughter of the kings and blessed him, 2 to whom also Abraham gave a tenth part of all, first being translated "kings of righteousness," and then also king of Salem, meaning "king of peace," 3 without father, without mother, without genealogy, having neither beginning of days nor end of life, but made like the Son of God, remains a priest continually. 4 Now consider how great this man was, to whom even the patriarch Abraham gave a tenth of the spoils. 5 And indeed those who are of the sons of Levi, who receive the priesthood, have a commandment to receive tithes from the people according to the law, that is, from their brethren, though they have come from the lions of Abraham, 6 but he whose genealogy is not derived from them received tithes from Abraham and blessed him who had the promises. 7 Now beyond all contradiction the lesser is blessed by the better 8 Here mortal men receive tithes, but there he receives them, of whom it is witnessed that he lives. 9 Even Levi, who receives tithes, paid tithes through Abraham, so to speak
